name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ianwalter/pnpm:v1.3.0
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: pnpm i
      - name: Lint
        run: pnpm lint
      # - name: Test
      #   run: yarn test
